export const legendList = [
  {
    label:'正常',
    color:'#0AF0FD',
    bg:'#1B3D9F'
  },
  {
    label:'故障',
    color:'#FF7729',
    bg:'#52320E'
  },
  {
    label:'告警',
    color:'#F2274A',
    bg:'#5E0C0C'
  },
]
// 环境监测终端
export const environmentalList = [
  {
    code:'WATER_IMMERSION',
    label:'水浸',
    icon:'icon-a-shuijin1'
  },
  {
    code:'WATER_MONITOR',
    label:'水位',
    icon:'icon-shuiwei1'
  },
  {
    code:'WATER_PUMP',
    label:'水泵',
    icon:'icon-shuibeng'
  },
  {
    code:'TEMPERATURE_HUMIDITY_SENSOR',
    label:'温湿度',
    icon:'icon-wenshidu_line'
  },
  {
    code:'MICROMETEOROGRAPH',
    label:'微气象',
    icon:'icon-weiqixiang'
  },
  {
    code:'SF6',
    label:'SF6',
    icon:'icon-SF6'
  },
]
// 动力控制终端
export const dynamicList = [
  {
    code:'AIR_BLOWER',
    label:'风机',
    icon:'icon-a-fengji1'
  },
  {
    code:'AIR_CONDITIONING',
    label:'空调',
    icon:'icon-kongtiao'
  },
  {
    code:'LIGHTING',
    label:'照明',
    icon:'icon-zhaoming'
  },
]
// 安全防范终端
export const safeList = [
  {
    code:'SMOKE_DETECTOR',
    label:'烟感',
    icon:'icon-yangan'
  },
  {
    code:'LOCK_CONTROL',
    label:'锁控',
    icon:'icon-suo'
  },
  {
    code:'ENTRANCE_GUARD',
    label:'门禁',
    icon:'icon-menjin1'
  },
  {
    code:'BURGLARY_ALARM_MASTER_PANEL',
    label:'防盗报警主机',
    icon:'icon-fangdaobaozhuji'
  },
  {
    code:'ELECTRONIC_FENCE',
    label:'电子围栏',
    icon:'icon-a-dianziweilan3x'
  },
  {
    code:'INFRARED_RADIATION',
    label:'红外对射',
    icon:'icon-hongwaiduishe1'
  },
  {
    code:'INFRARED_DUAL_DISCRIMINATION',
    label:'红外双鉴',
    icon:'icon-hongwaishuangjian1'
  },
  {
    code:'ANTI_DRONE',
    label:'反无人机防御',
    icon:'icon-zhuangbei-wurenji2'
  },
]
// 主设备终端
export const equipmentList = [
  {
    code:'TRANSFORMER',
    label:'变压器',
    icon:'icon-bianyaqi'
  },
  {
    code:'CIRCUIT_BREAKER',
    label:'断路器',
    icon:'icon-duanluqi'
  },
  {
    code:'LIGHTNING_ARRESTED',
    label:'避雷器',
    icon:'icon-bileiqi'
  },
]
